version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=HRshanto31
      - POSTGRES_DB=orderManagement
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=HRshanto31
      - DB_NAME=orderManagement
      - DB_PORT=5432
      - DB_SSLMODE=disable
      - JWT_KEY=secret
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
volumes:
  postgres_data:
